### COLORS ###

DEF_COLOR = \033[0;39m
GRAY = \033[0;90m
RED = \033[0;91m
GREEN = \033[0;92m
YELLOW = \033[0;93m
BLUE = \033[0;94m
MAGENTA = \033[0;95m
CYAN = \033[0;96m
WHITE = \033[0;97m

### VARIABLES ###

NAME = libasm.a
TEST_NAME = test_libasm

ASM := nasm
CC := gcc
AR := ar rcs

ASMFLAGS := -felf64
CFLAGS := -Wall -Wextra -Werror

ASM_DIR = src
TEST_DIR = test

ASM_OBJ_DIR = $(ASM_DIR)/obj
TEST_OBJ_DIR = $(TEST_DIR)/obj

ASM_FILES := ft_strlen.s
TEST_FILES := main.c strlen.c

ASM_SRC := $(addprefix $(ASM_DIR)/, $(ASM_FILES))
TEST_SRC := $(addprefix $(TEST_DIR)/, $(TEST_FILES))

ASM_OBJ := $(addprefix $(ASM_OBJ_DIR)/, $(ASM_FILES:.s=.o))
TEST_OBJ := $(addprefix $(TEST_OBJ_DIR)/, $(TEST_FILES:.c=.o))

### COMPILATION ###

all: $(NAME)

$(NAME): $(ASM_OBJ)
	$(AR) $(NAME) $(ASM_OBJ)
	@echo "$(GREEN)-> $(NAME) archive ready.$(DEF_COLOR)"

$(ASM_OBJ_DIR)/%.o: $(ASM_DIR)/%.s | $(ASM_OBJ_DIR)
	$(ASM) $(ASMFLAGS) $< -o $@
	@echo "$(GREEN)-> $@ assembled.$(DEF_COLOR)"

$(TEST_OBJ_DIR)/%.o: $(TEST_DIR)/%.c | $(TEST_OBJ_DIR)
	$(CC) $(CFLAGS) -c $< -o $@
	@echo "$(GREEN)-> $@ compiled.$(DEF_COLOR)"

$(ASM_OBJ_DIR):
	@mkdir -p $(ASM_OBJ_DIR)

$(TEST_OBJ_DIR):
	@mkdir -p $(TEST_OBJ_DIR)

$(TEST_NAME): $(NAME) $(TEST_OBJ)
	$(CC) $(CFLAGS) $(TEST_OBJ) -L. -lasm -o $(TEST_NAME)
	@echo "$(GREEN)-> $(TEST_NAME) compiled.$(DEF_COLOR)"

### MEMO ###
# 	Special variables :
#		$@	Represents the target file that is being generated by the rule
#		$<	Represents the first dependency of the rule
#		$^	Represents all the dependencies of the rule, separated by spaces.
#		$?	Represents a list of dependencies that are newer than the target file.
#		$*	Represents the stem of the target filename (without the extension)

### RULES ###

test: $(TEST_NAME)

clean:
	@rm -rf $(ASM_OBJ_DIR) $(TEST_OBJ_DIR)
	@echo "$(RED)Libasm object files removed.$(DEF_COLOR)"

fclean: clean
	@rm -f $(NAME)
	@rm -f $(TEST_NAME)
	@echo "$(RED)Libasm archive and executables removed.$(DEF_COLOR)"

re: fclean all
	@echo "$(CYAN)Libasm cleaned and rebuilt from scratch.$(DEF_COLOR)"

.PHONY: all clean fclean re test